package org.example.enums;

public enum Role {
    ROLE_ADMINISTRATEUR,
    ROLE_GERANT,
    ROLE_COMMERCIAL,
    ROLE_INTERVENANT_DEPOT,
    ROLE_INTERVENANT_COMMERCIAL,
    ROLE_INTERVENANT_ELECTROMECANIQUE,
    ROLE_TECHNICIEN,
    ROLE_CHAUFFEUR
}
